name: Run Gradle on PRs
on: pull_request

jobs:
  gradle:
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
  
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build
        run: ./gradlew build --stacktrace

      - name: Upload allTests results
        uses: actions/upload-artifact@v2.2.3
        with:
          name: allTests
          path: ./**/build/reports/tests/allTests
